# Generated by Django 3.2.11 on 2025-05-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0033_alter_contribution_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(default='0', max_length=250),
            preserve_default=False,
        ),
    ]
