# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
          
      - name: Install dependencies
        run: pip install -r donationdb/requirements.txt
        
      - name: Run tests
        run: cd donationdb/ && python manage.py test
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
          DONATIONDB_API_KEY: ${{ secrets.DONATIONDB_API_KEY }}
          DONATIONDB_URL: ${{ secrets.DONATIONDB_URL }}
          HEROKU_APP_VISION_TF_FI: vision-tf-fi
          HEROKU_APP_STAGING_VISION_TF_FI: staging-vision-tf-fi
          HEROKU_OAUTH_TOKEN: abcd-efgh-ijkl-mnop
          CI: ${{ secrets.CI }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          PAYTRAIL_ACCOUNT_ID: 375917
          PAYTRAIL_ACCOUNT_SECRET: SAIPPUAKAUPPIAS
